name: Entrenar y Publicar Modelo

on:
  push:
    branches:
      - main # Se activa con cada push a la rama principal

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Obtener el código del repositorio
      - uses: actions/checkout@v4

      # Paso 2: Configurar el entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Paso 3: Instalar las librerías necesarias
      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      # Paso 4: Entrenar el modelo (esto crea model.pkl y metrics.txt)
      - name: Train the Model
        run: python train.py

      # Paso 5: Publicar los artefactos en Hugging Face
      - name: Publish to Hugging Face Hub
        env:
          # El token se obtiene de los secretos de GitHub
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import HfApi
          import os

          # Inicializa la conexión con la API de Hugging Face
          api = HfApi()
          repo_id = 'Juan2233/modelo-iris' # Tu ID de repositorio
          token = os.environ.get('HF_TOKEN')

          print(f'Subiendo archivos al repositorio: {repo_id}')

          # Sube el modelo
          api.upload_file(
              path_or_fileobj='model.pkl',
              path_in_repo='model.pkl', # Nombre del archivo en el Hub
              repo_id=repo_id,
              token=token
          )

          # Sube las métricas
          api.upload_file(
              path_or_fileobj='metrics.txt',
              path_in_repo='metrics.txt', # Nombre del archivo en el Hub
              repo_id=repo_id,
              token=token
          )

          print('¡Archivos subidos con éxito!')
          "
