name: Train and Publish Model

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Train the Model
        run: python train.py

      - name: Publish to Hugging Face Hub
        uses: huggingface/hub-action@v4
        with:
          # Esta línea usa el secreto que creaste.
          hf_token: ${{ secrets.HF_TOKEN }}
          
          # Esta línea apunta a tu repositorio, que ya existe.
          repo_id: Juan2233/modelo-iris
          
          # Los archivos que se van a subir.
          files_to_deploy: >
            model.pkl
            metrics.txt
