name: Train and Publish Model

on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Train the Model
        run: python train.py

      # Copiamos SOLO lo que queremos subir al Hub
      - name: Prepare artifacts for Hugging Face
        run: |
          mkdir -p artifacts
          cp model.pkl artifacts/
          cp metrics.txt artifacts/
          # opcional: crea una tarjeta de modelo si no existe
          [ -f README.md ] && cp README.md artifacts/ || echo "# modelo-iris" > artifacts/README.md

      - name: Publish to Hugging Face Hub (model)
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: Juan2233/modelo-iris
          repo_type: model
          subdirectory: artifacts
          hf_token: ${{ secrets.HF_TOKEN }}
